### ISSUE TITLE
代码中的几个问题

### ISSUE THREAD

**Issue by JiantingFeng** [Roderickzzc/Pdo-econv-pytorch#1]
你好，我最近也在尝试复现这篇论文，有几个问题需要请教。
1.请问代码中的num_inputs和num_outputs是什么意思
2.num_inputs和num_outputs取值分别为56和7有什么含义

**Comment by Zhang-Zecheng** [comment]
不好意思 我好久没做这个了，有错误还请指正。首先定义了一个新的conv层，有点像nn.conv2d。num_inputs, num_outputs应该是in_Channel和out_channel。7是原论文中rotated mnist采用的参数，56是经过经过pdo之后（channel数乘以8）出来的。
